package org.elkoserver.foundation.net

/**
 * Manage network connections between this server and other entities.
 */
object Communication {
    /** Maximum length message that a connection will be able to receive.  */
    const val MAX_MSG_LENGTH = 1024 * 1024

    /**
     * Special debug support: if this flag is set to true, errors generated by
     * received messages will result in a 'debug' message being sent in reply.
     * Normally (when the flag is false), from the sender's perspective such
     * errors will be silently swallowed.
     */
    @JvmField
    var TheDebugReplyFlag = false
}
