package org.elkoserver.foundation.net;

/**
 * Manage network connections between this server and other entities.
 */
public class Communication {
    /** Maximum length message that a connection will be able to receive. */
    public static final int MAX_MSG_LENGTH = 1024*1024;

    /**
     * Special debug support: if this flag is set to true, errors generated by
     * received messages will result in a 'debug' message being sent in reply.
     * Normally (when the flag is false), from the sender's perspective such
     * errors will be silently swallowed.
     */
    public static boolean TheDebugReplyFlag = false;
}
